import crypto from "crypto";
import { getEnv } from '@healthcare/shared/config';
import { clinicConfigurationDefinition } from '@healthcare/shared/config/clinic-configuration';
import { listEffectiveClinicConfiguration } from './clinic-configuration.js';
import { db } from '../core/database.js';
import { logAudit } from './audit.js';
import { providerRuntimeOrFallback } from './clinic-provider-runtime.js';
import { assertClinicProviderOperation } from './clinic-provider-capabilities.js';
import { moneyToCents } from './payment-callbacks.js';

const DEFAULT_CURRENCY = String(clinicConfigurationDefinition('clinic.finance.currency')?.defaultValue || '');

const CURRENCIES: Record<string, { symbol: string; rate: number }> = {
  SAR: { symbol: 'ر.س', rate: 1 },
  USD: { symbol: '$', rate: 3.75 },
  EUR: { symbol: '€', rate: 4.05 },
  AED: { symbol: 'د.إ', rate: 1.02 },
  EGP: { symbol: 'ج.م', rate: 0.12 },
};

export function getCurrencyInfo(code: string) {
  return CURRENCIES[code.toUpperCase()] || CURRENCIES[DEFAULT_CURRENCY] || { symbol: DEFAULT_CURRENCY, rate: 1 };
}

export function convertCurrency(amount: number, from: string, to: string): number {
  const fromInfo = getCurrencyInfo(from);
  const toInfo = getCurrencyInfo(to);
  const sarAmount = amount / fromInfo.rate;
  return Math.round(sarAmount * toInfo.rate * 100) / 100;
}

interface PaymentResult {
  success: boolean;
  paymentId?: string;
  redirectUrl?: string;
  reference?: string;
  error?: string;
}

// Generate Fawry payment reference
export function generateFawryPayment(invoiceId: string, amount: number, customerPhone: string, customerName: string, customerEmail: string): PaymentResult {
  const env = getEnv();
  if (!env.FAWRY_MERCHANT_CODE) {
    return { success: false, error: 'Fawry is not configured. Add FAWRY_MERCHANT_CODE to environment.' };
  }

  const merchantCode = env.FAWRY_MERCHANT_CODE;
  const merchantRef = `INV-${invoiceId.substring(0, 8)}-${Date.now()}`;
  const securityKey = env.FAWRY_SECURITY_KEY || '';

  // In production, this would call Fawry API
  // For now, generate the payment reference that would be sent to Fawry
  const paymentRef = `FR-${Date.now()}-${crypto.randomBytes(4).toString("hex").toUpperCase()}`;

  return {
    success: true,
    paymentId: paymentRef,
    reference: merchantRef,
    redirectUrl: `https://atfawry.com/ECommercePlugin/pay?merchantCode=${merchantCode}&merchantRefNumber=${merchantRef}&amount=${amount}&currencyCode=EGP&description=Invoice%20Payment&customerEmail=${encodeURIComponent(customerEmail)}&customerPhone=${encodeURIComponent(customerPhone)}`,
  };
}

// Generate InstaPay payment link (Egypt's instant payment network)
export function generateInstaPayPayment(amount: number, merchantWallet: string): PaymentResult {
  const env = getEnv();
  if (!env.INSTAPAY_WALLET) {
    return { success: false, error: 'InstaPay is not configured. Add INSTAPAY_WALLET to environment.' };
  }

  // InstaPay uses QR codes generated by the merchant's bank
  // The wallet number is the merchant's registered InstaPay wallet
  return {
    success: true,
    reference: `IP-${Date.now()}`,
    redirectUrl: `instapay://send?wallet=${env.INSTAPAY_WALLET}&amount=${amount}`,
    paymentId: `IPAY-${Date.now()}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`,
  };
}

// Generate Egyptian E-Invoicing QR Code data (ETA format)
export function generateEtaQrCode( sellerName: string, taxRegistrationNumber: string, timestamp: string, total: number, taxTotal: number ): string {
  // ETA QR code format (TLV - Tag Length Value)
  // Tag 1: Seller Name
  // Tag 2: VAT Registration Number
  // Tag 3: Time Stamp
  // Tag 4: Invoice Total
  // Tag 5: Total VAT
  const tlv = {
    1: sellerName,
    2: taxRegistrationNumber,
    3: timestamp,
    4: total.toFixed(2),
    5: taxTotal.toFixed(2),
  };
  // Return base64-encoded JSON (simplified — in production, use proper TLV encoding)
  return Buffer.from(JSON.stringify(tlv)).toString('base64');
}

// Stripe payment
export async function createStripePayment(invoiceId: string, amount: number, currency: string, tenantId: string): Promise<PaymentResult> {
  const env = getEnv();
  try {
    assertClinicProviderOperation('stripe', 'stripe.checkout.create');
    const runtime = await providerRuntimeOrFallback(tenantId, 'stripe', {
      secrets: { secretKey: env.STRIPE_SECRET_KEY || '' },
    });
    if (runtime?.status === 'disabled') return { success: false, error: 'Stripe is disabled for this clinic.' };
    const stripeSecretKey = runtime?.secrets.secretKey;
    if (!stripeSecretKey) return { success: false, error: 'Stripe is not configured for this clinic.' };
    const stripe = require('stripe')(stripeSecretKey);
    const invoice = await db('invoices').where({ id: invoiceId, tenant_id: tenantId }).whereNull('deleted_at').first();
    if (!invoice) return { success: false, error: 'Invoice not found' };
    const amountCents = moneyToCents(amount);
    const totalCents = moneyToCents(invoice.total);
    const paidCents = moneyToCents(invoice.paid);
    if (amountCents === null || totalCents === null || paidCents === null || paidCents + amountCents > totalCents) {
      return { success: false, error: 'Payment amount exceeds the invoice amount due.' };
    }
    const patient = await db('patients').where({ id: invoice.patient_id, tenant_id: tenantId }).first();
    const tenant = await db('tenants').where({ id: tenantId }).first();
    const clinicName = (await listEffectiveClinicConfiguration(tenantId))
      .find((entry) => entry.key === 'clinic.profile.display_name')?.value;
    const displayName = typeof clinicName === 'string' && clinicName.trim()
      ? clinicName.trim()
      : tenant?.name || 'Clinic';
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      customer_email: patient?.email || undefined,
      line_items: [{
        price_data: {
          currency: currency.toLowerCase(),
          product_data: { name: `Invoice ${invoice.invoice_number} — ${displayName}` },
          unit_amount: Math.round(amount * 100),
        },
        quantity: 1,
      }],
      mode: 'payment',
      metadata: { invoiceId, tenantId },
      success_url: `${env.APP_URL}/billing?payment=success&invoice=${invoiceId}`,
      cancel_url: `${env.APP_URL}/billing?payment=cancelled&invoice=${invoiceId}`,
    });
    await db('payment_transactions').insert({ tenant_id: tenantId, invoice_id: invoiceId, amount, method: 'online', provider_key: 'stripe', reference: session.id, notes: 'Stripe checkout', status: 'pending', updated_at: new Date() });
    await logAudit({ tenantId, action: 'payment.stripe.create', entityType: 'invoice', entityId: invoiceId, metadata: { amount, currency } });
    return { success: true, paymentId: session.id, redirectUrl: session.url };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

// Confirm Stripe payment (webhook). This function is intentionally idempotent:
// one provider transaction can finalize one invoice payment at most once.
export async function confirmStripePayment(sessionId: string): Promise<boolean> {
  const env = getEnv();
  try {
    const payment = await db('payment_transactions')
      .where({ provider_key: 'stripe', reference: sessionId })
      .select('id', 'tenant_id', 'invoice_id', 'amount', 'status')
      .first() as {
        id: string;
        tenant_id: string;
        invoice_id: string | null;
        amount: number | string;
        status: string;
      } | undefined;
    if (!payment?.tenant_id || !payment.invoice_id) return false;

    assertClinicProviderOperation('stripe', 'stripe.payment.confirm');
    const runtime = await providerRuntimeOrFallback(payment.tenant_id, 'stripe', {
      secrets: { secretKey: env.STRIPE_SECRET_KEY || '' },
    });
    if (runtime?.status === 'disabled') return false;
    const stripeSecretKey = runtime?.secrets.secretKey;
    if (!stripeSecretKey) return false;

    const stripe = require('stripe')(stripeSecretKey);
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== 'paid') return false;
    const metadata = session.metadata && typeof session.metadata === 'object' ? session.metadata as Record<string, string> : {};
    if (metadata.tenantId !== payment.tenant_id || metadata.invoiceId !== payment.invoice_id) return false;

    const transactionAmountCents = moneyToCents(payment.amount);
    const providerAmountCents = moneyToCents(session.amount_total === null ? null : Number(session.amount_total) / 100);
    if (transactionAmountCents === null || providerAmountCents === null || transactionAmountCents !== providerAmountCents) return false;

    await db.transaction(async (trx) => {
      const lockedPayment = await trx('payment_transactions')
        .where({ id: payment.id, tenant_id: payment.tenant_id, provider_key: 'stripe', reference: sessionId })
        .forUpdate()
        .first() as { status: string; invoice_id: string | null; amount: number | string } | undefined;
      if (!lockedPayment || lockedPayment.invoice_id !== payment.invoice_id) throw new Error('Stripe payment transaction changed');
      if (lockedPayment.status === 'completed') return;
      if (lockedPayment.status !== 'pending') throw new Error('Stripe payment transaction is not pending');

      const invoice = await trx('invoices')
        .where({ id: lockedPayment.invoice_id, tenant_id: payment.tenant_id })
        .whereNull('deleted_at')
        .forUpdate()
        .first() as { id: string; total: number | string; paid: number | string } | undefined;
      if (!invoice) throw new Error('Invoice not found');

      const totalCents = moneyToCents(invoice.total);
      const currentPaidCents = moneyToCents(invoice.paid);
      const paidCents = moneyToCents(lockedPayment.amount);
      if (totalCents === null || currentPaidCents === null || paidCents === null || currentPaidCents + paidCents > totalCents) {
        throw new Error('Stripe payment amount exceeds invoice due amount');
      }

      const newPaidCents = currentPaidCents + paidCents;
      const newDueCents = totalCents - newPaidCents;
      await trx('invoices').where({ id: invoice.id, tenant_id: payment.tenant_id }).update({
        paid: newPaidCents / 100,
        due: newDueCents / 100,
        status: newDueCents === 0 ? 'paid' : 'partial',
        payment_method: 'online',
        paid_at: new Date(),
      });
      await trx('payment_transactions').where({ id: payment.id, tenant_id: payment.tenant_id, status: 'pending' }).update({ status: 'completed' });
    });

    await logAudit({ tenantId: payment.tenant_id, action: 'payment.stripe.confirm', entityType: 'invoice', entityId: payment.invoice_id });
    return true;
  } catch {
    return false;
  }
}

export function generatePaymentLink(invoiceId: string, tenantSlug: string): string {
  const env = getEnv();
  return `${env.APP_URL}/pay/${tenantSlug}/${invoiceId}`;
}
